# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /data/data/com.termux/files/usr/bin/sh

# The CMake executable.
CMAKE_COMMAND = /data/data/com.termux/files/usr/bin/cmake

# The command to remove a file.
RM = /data/data/com.termux/files/usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /data/data/com.termux/files/home/Nova

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /data/data/com.termux/files/home/Nova

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/data/data/com.termux/files/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/data/data/com.termux/files/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /data/data/com.termux/files/home/Nova/CMakeFiles /data/data/com.termux/files/home/Nova//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /data/data/com.termux/files/home/Nova/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named nova

# Build rule for target.
nova: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nova
.PHONY : nova

# fast build rule for target.
nova/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/build
.PHONY : nova/fast

advanced_ai_core/ai_core.o: advanced_ai_core/ai_core.cpp.o
.PHONY : advanced_ai_core/ai_core.o

# target to build an object file
advanced_ai_core/ai_core.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/advanced_ai_core/ai_core.cpp.o
.PHONY : advanced_ai_core/ai_core.cpp.o

advanced_ai_core/ai_core.i: advanced_ai_core/ai_core.cpp.i
.PHONY : advanced_ai_core/ai_core.i

# target to preprocess a source file
advanced_ai_core/ai_core.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/advanced_ai_core/ai_core.cpp.i
.PHONY : advanced_ai_core/ai_core.cpp.i

advanced_ai_core/ai_core.s: advanced_ai_core/ai_core.cpp.s
.PHONY : advanced_ai_core/ai_core.s

# target to generate assembly for a file
advanced_ai_core/ai_core.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/advanced_ai_core/ai_core.cpp.s
.PHONY : advanced_ai_core/ai_core.cpp.s

analytics/nova_telemetry.o: analytics/nova_telemetry.cpp.o
.PHONY : analytics/nova_telemetry.o

# target to build an object file
analytics/nova_telemetry.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/analytics/nova_telemetry.cpp.o
.PHONY : analytics/nova_telemetry.cpp.o

analytics/nova_telemetry.i: analytics/nova_telemetry.cpp.i
.PHONY : analytics/nova_telemetry.i

# target to preprocess a source file
analytics/nova_telemetry.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/analytics/nova_telemetry.cpp.i
.PHONY : analytics/nova_telemetry.cpp.i

analytics/nova_telemetry.s: analytics/nova_telemetry.cpp.s
.PHONY : analytics/nova_telemetry.s

# target to generate assembly for a file
analytics/nova_telemetry.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/analytics/nova_telemetry.cpp.s
.PHONY : analytics/nova_telemetry.cpp.s

blockchain_web3/nova_web3.o: blockchain_web3/nova_web3.cpp.o
.PHONY : blockchain_web3/nova_web3.o

# target to build an object file
blockchain_web3/nova_web3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/blockchain_web3/nova_web3.cpp.o
.PHONY : blockchain_web3/nova_web3.cpp.o

blockchain_web3/nova_web3.i: blockchain_web3/nova_web3.cpp.i
.PHONY : blockchain_web3/nova_web3.i

# target to preprocess a source file
blockchain_web3/nova_web3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/blockchain_web3/nova_web3.cpp.i
.PHONY : blockchain_web3/nova_web3.cpp.i

blockchain_web3/nova_web3.s: blockchain_web3/nova_web3.cpp.s
.PHONY : blockchain_web3/nova_web3.s

# target to generate assembly for a file
blockchain_web3/nova_web3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/blockchain_web3/nova_web3.cpp.s
.PHONY : blockchain_web3/nova_web3.cpp.s

compiler/bytecode.o: compiler/bytecode.cpp.o
.PHONY : compiler/bytecode.o

# target to build an object file
compiler/bytecode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/compiler/bytecode.cpp.o
.PHONY : compiler/bytecode.cpp.o

compiler/bytecode.i: compiler/bytecode.cpp.i
.PHONY : compiler/bytecode.i

# target to preprocess a source file
compiler/bytecode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/compiler/bytecode.cpp.i
.PHONY : compiler/bytecode.cpp.i

compiler/bytecode.s: compiler/bytecode.cpp.s
.PHONY : compiler/bytecode.s

# target to generate assembly for a file
compiler/bytecode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/compiler/bytecode.cpp.s
.PHONY : compiler/bytecode.cpp.s

compiler/lexer.o: compiler/lexer.cpp.o
.PHONY : compiler/lexer.o

# target to build an object file
compiler/lexer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/compiler/lexer.cpp.o
.PHONY : compiler/lexer.cpp.o

compiler/lexer.i: compiler/lexer.cpp.i
.PHONY : compiler/lexer.i

# target to preprocess a source file
compiler/lexer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/compiler/lexer.cpp.i
.PHONY : compiler/lexer.cpp.i

compiler/lexer.s: compiler/lexer.cpp.s
.PHONY : compiler/lexer.s

# target to generate assembly for a file
compiler/lexer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/compiler/lexer.cpp.s
.PHONY : compiler/lexer.cpp.s

compiler/main.o: compiler/main.cpp.o
.PHONY : compiler/main.o

# target to build an object file
compiler/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/compiler/main.cpp.o
.PHONY : compiler/main.cpp.o

compiler/main.i: compiler/main.cpp.i
.PHONY : compiler/main.i

# target to preprocess a source file
compiler/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/compiler/main.cpp.i
.PHONY : compiler/main.cpp.i

compiler/main.s: compiler/main.cpp.s
.PHONY : compiler/main.s

# target to generate assembly for a file
compiler/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/compiler/main.cpp.s
.PHONY : compiler/main.cpp.s

compiler/parser.o: compiler/parser.cpp.o
.PHONY : compiler/parser.o

# target to build an object file
compiler/parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/compiler/parser.cpp.o
.PHONY : compiler/parser.cpp.o

compiler/parser.i: compiler/parser.cpp.i
.PHONY : compiler/parser.i

# target to preprocess a source file
compiler/parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/compiler/parser.cpp.i
.PHONY : compiler/parser.cpp.i

compiler/parser.s: compiler/parser.cpp.s
.PHONY : compiler/parser.s

# target to generate assembly for a file
compiler/parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/compiler/parser.cpp.s
.PHONY : compiler/parser.cpp.s

deployment/nova_deploy.o: deployment/nova_deploy.cpp.o
.PHONY : deployment/nova_deploy.o

# target to build an object file
deployment/nova_deploy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/deployment/nova_deploy.cpp.o
.PHONY : deployment/nova_deploy.cpp.o

deployment/nova_deploy.i: deployment/nova_deploy.cpp.i
.PHONY : deployment/nova_deploy.i

# target to preprocess a source file
deployment/nova_deploy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/deployment/nova_deploy.cpp.i
.PHONY : deployment/nova_deploy.cpp.i

deployment/nova_deploy.s: deployment/nova_deploy.cpp.s
.PHONY : deployment/nova_deploy.s

# target to generate assembly for a file
deployment/nova_deploy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/deployment/nova_deploy.cpp.s
.PHONY : deployment/nova_deploy.cpp.s

docs/nova_docgen.o: docs/nova_docgen.cpp.o
.PHONY : docs/nova_docgen.o

# target to build an object file
docs/nova_docgen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/docs/nova_docgen.cpp.o
.PHONY : docs/nova_docgen.cpp.o

docs/nova_docgen.i: docs/nova_docgen.cpp.i
.PHONY : docs/nova_docgen.i

# target to preprocess a source file
docs/nova_docgen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/docs/nova_docgen.cpp.i
.PHONY : docs/nova_docgen.cpp.i

docs/nova_docgen.s: docs/nova_docgen.cpp.s
.PHONY : docs/nova_docgen.s

# target to generate assembly for a file
docs/nova_docgen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/docs/nova_docgen.cpp.s
.PHONY : docs/nova_docgen.cpp.s

experiments/quantum/nova_quantum.o: experiments/quantum/nova_quantum.cpp.o
.PHONY : experiments/quantum/nova_quantum.o

# target to build an object file
experiments/quantum/nova_quantum.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/experiments/quantum/nova_quantum.cpp.o
.PHONY : experiments/quantum/nova_quantum.cpp.o

experiments/quantum/nova_quantum.i: experiments/quantum/nova_quantum.cpp.i
.PHONY : experiments/quantum/nova_quantum.i

# target to preprocess a source file
experiments/quantum/nova_quantum.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/experiments/quantum/nova_quantum.cpp.i
.PHONY : experiments/quantum/nova_quantum.cpp.i

experiments/quantum/nova_quantum.s: experiments/quantum/nova_quantum.cpp.s
.PHONY : experiments/quantum/nova_quantum.s

# target to generate assembly for a file
experiments/quantum/nova_quantum.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/experiments/quantum/nova_quantum.cpp.s
.PHONY : experiments/quantum/nova_quantum.cpp.s

full_stack_dev/hyperweb.o: full_stack_dev/hyperweb.cpp.o
.PHONY : full_stack_dev/hyperweb.o

# target to build an object file
full_stack_dev/hyperweb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/full_stack_dev/hyperweb.cpp.o
.PHONY : full_stack_dev/hyperweb.cpp.o

full_stack_dev/hyperweb.i: full_stack_dev/hyperweb.cpp.i
.PHONY : full_stack_dev/hyperweb.i

# target to preprocess a source file
full_stack_dev/hyperweb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/full_stack_dev/hyperweb.cpp.i
.PHONY : full_stack_dev/hyperweb.cpp.i

full_stack_dev/hyperweb.s: full_stack_dev/hyperweb.cpp.s
.PHONY : full_stack_dev/hyperweb.s

# target to generate assembly for a file
full_stack_dev/hyperweb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/full_stack_dev/hyperweb.cpp.s
.PHONY : full_stack_dev/hyperweb.cpp.s

game_engine/nova_game.o: game_engine/nova_game.cpp.o
.PHONY : game_engine/nova_game.o

# target to build an object file
game_engine/nova_game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/game_engine/nova_game.cpp.o
.PHONY : game_engine/nova_game.cpp.o

game_engine/nova_game.i: game_engine/nova_game.cpp.i
.PHONY : game_engine/nova_game.i

# target to preprocess a source file
game_engine/nova_game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/game_engine/nova_game.cpp.i
.PHONY : game_engine/nova_game.cpp.i

game_engine/nova_game.s: game_engine/nova_game.cpp.s
.PHONY : game_engine/nova_game.s

# target to generate assembly for a file
game_engine/nova_game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/game_engine/nova_game.cpp.s
.PHONY : game_engine/nova_game.cpp.s

graphics/nova_graphics.o: graphics/nova_graphics.cpp.o
.PHONY : graphics/nova_graphics.o

# target to build an object file
graphics/nova_graphics.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/graphics/nova_graphics.cpp.o
.PHONY : graphics/nova_graphics.cpp.o

graphics/nova_graphics.i: graphics/nova_graphics.cpp.i
.PHONY : graphics/nova_graphics.i

# target to preprocess a source file
graphics/nova_graphics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/graphics/nova_graphics.cpp.i
.PHONY : graphics/nova_graphics.cpp.i

graphics/nova_graphics.s: graphics/nova_graphics.cpp.s
.PHONY : graphics/nova_graphics.s

# target to generate assembly for a file
graphics/nova_graphics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/graphics/nova_graphics.cpp.s
.PHONY : graphics/nova_graphics.cpp.s

hardware_control/embedded_targets/nova_iot.o: hardware_control/embedded_targets/nova_iot.cpp.o
.PHONY : hardware_control/embedded_targets/nova_iot.o

# target to build an object file
hardware_control/embedded_targets/nova_iot.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/hardware_control/embedded_targets/nova_iot.cpp.o
.PHONY : hardware_control/embedded_targets/nova_iot.cpp.o

hardware_control/embedded_targets/nova_iot.i: hardware_control/embedded_targets/nova_iot.cpp.i
.PHONY : hardware_control/embedded_targets/nova_iot.i

# target to preprocess a source file
hardware_control/embedded_targets/nova_iot.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/hardware_control/embedded_targets/nova_iot.cpp.i
.PHONY : hardware_control/embedded_targets/nova_iot.cpp.i

hardware_control/embedded_targets/nova_iot.s: hardware_control/embedded_targets/nova_iot.cpp.s
.PHONY : hardware_control/embedded_targets/nova_iot.s

# target to generate assembly for a file
hardware_control/embedded_targets/nova_iot.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/hardware_control/embedded_targets/nova_iot.cpp.s
.PHONY : hardware_control/embedded_targets/nova_iot.cpp.s

ide/vscode_extension/nova_lsp.o: ide/vscode_extension/nova_lsp.cpp.o
.PHONY : ide/vscode_extension/nova_lsp.o

# target to build an object file
ide/vscode_extension/nova_lsp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/ide/vscode_extension/nova_lsp.cpp.o
.PHONY : ide/vscode_extension/nova_lsp.cpp.o

ide/vscode_extension/nova_lsp.i: ide/vscode_extension/nova_lsp.cpp.i
.PHONY : ide/vscode_extension/nova_lsp.i

# target to preprocess a source file
ide/vscode_extension/nova_lsp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/ide/vscode_extension/nova_lsp.cpp.i
.PHONY : ide/vscode_extension/nova_lsp.cpp.i

ide/vscode_extension/nova_lsp.s: ide/vscode_extension/nova_lsp.cpp.s
.PHONY : ide/vscode_extension/nova_lsp.s

# target to generate assembly for a file
ide/vscode_extension/nova_lsp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/ide/vscode_extension/nova_lsp.cpp.s
.PHONY : ide/vscode_extension/nova_lsp.cpp.s

networking/nova_network.o: networking/nova_network.cpp.o
.PHONY : networking/nova_network.o

# target to build an object file
networking/nova_network.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/networking/nova_network.cpp.o
.PHONY : networking/nova_network.cpp.o

networking/nova_network.i: networking/nova_network.cpp.i
.PHONY : networking/nova_network.i

# target to preprocess a source file
networking/nova_network.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/networking/nova_network.cpp.i
.PHONY : networking/nova_network.cpp.i

networking/nova_network.s: networking/nova_network.cpp.s
.PHONY : networking/nova_network.s

# target to generate assembly for a file
networking/nova_network.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/networking/nova_network.cpp.s
.PHONY : networking/nova_network.cpp.s

operating_system_layer/j_kernel.o: operating_system_layer/j_kernel.cpp.o
.PHONY : operating_system_layer/j_kernel.o

# target to build an object file
operating_system_layer/j_kernel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/operating_system_layer/j_kernel.cpp.o
.PHONY : operating_system_layer/j_kernel.cpp.o

operating_system_layer/j_kernel.i: operating_system_layer/j_kernel.cpp.i
.PHONY : operating_system_layer/j_kernel.i

# target to preprocess a source file
operating_system_layer/j_kernel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/operating_system_layer/j_kernel.cpp.i
.PHONY : operating_system_layer/j_kernel.cpp.i

operating_system_layer/j_kernel.s: operating_system_layer/j_kernel.cpp.s
.PHONY : operating_system_layer/j_kernel.s

# target to generate assembly for a file
operating_system_layer/j_kernel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/operating_system_layer/j_kernel.cpp.s
.PHONY : operating_system_layer/j_kernel.cpp.s

package_ecosystem/nova_pm.o: package_ecosystem/nova_pm.cpp.o
.PHONY : package_ecosystem/nova_pm.o

# target to build an object file
package_ecosystem/nova_pm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/package_ecosystem/nova_pm.cpp.o
.PHONY : package_ecosystem/nova_pm.cpp.o

package_ecosystem/nova_pm.i: package_ecosystem/nova_pm.cpp.i
.PHONY : package_ecosystem/nova_pm.i

# target to preprocess a source file
package_ecosystem/nova_pm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/package_ecosystem/nova_pm.cpp.i
.PHONY : package_ecosystem/nova_pm.cpp.i

package_ecosystem/nova_pm.s: package_ecosystem/nova_pm.cpp.s
.PHONY : package_ecosystem/nova_pm.s

# target to generate assembly for a file
package_ecosystem/nova_pm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/package_ecosystem/nova_pm.cpp.s
.PHONY : package_ecosystem/nova_pm.cpp.s

physics_engine/nova_physics.o: physics_engine/nova_physics.cpp.o
.PHONY : physics_engine/nova_physics.o

# target to build an object file
physics_engine/nova_physics.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/physics_engine/nova_physics.cpp.o
.PHONY : physics_engine/nova_physics.cpp.o

physics_engine/nova_physics.i: physics_engine/nova_physics.cpp.i
.PHONY : physics_engine/nova_physics.i

# target to preprocess a source file
physics_engine/nova_physics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/physics_engine/nova_physics.cpp.i
.PHONY : physics_engine/nova_physics.cpp.i

physics_engine/nova_physics.s: physics_engine/nova_physics.cpp.s
.PHONY : physics_engine/nova_physics.s

# target to generate assembly for a file
physics_engine/nova_physics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/physics_engine/nova_physics.cpp.s
.PHONY : physics_engine/nova_physics.cpp.s

robotics_control/robot_core.o: robotics_control/robot_core.cpp.o
.PHONY : robotics_control/robot_core.o

# target to build an object file
robotics_control/robot_core.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/robotics_control/robot_core.cpp.o
.PHONY : robotics_control/robot_core.cpp.o

robotics_control/robot_core.i: robotics_control/robot_core.cpp.i
.PHONY : robotics_control/robot_core.i

# target to preprocess a source file
robotics_control/robot_core.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/robotics_control/robot_core.cpp.i
.PHONY : robotics_control/robot_core.cpp.i

robotics_control/robot_core.s: robotics_control/robot_core.cpp.s
.PHONY : robotics_control/robot_core.s

# target to generate assembly for a file
robotics_control/robot_core.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/robotics_control/robot_core.cpp.s
.PHONY : robotics_control/robot_core.cpp.s

runtime/ffi.o: runtime/ffi.cpp.o
.PHONY : runtime/ffi.o

# target to build an object file
runtime/ffi.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/runtime/ffi.cpp.o
.PHONY : runtime/ffi.cpp.o

runtime/ffi.i: runtime/ffi.cpp.i
.PHONY : runtime/ffi.i

# target to preprocess a source file
runtime/ffi.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/runtime/ffi.cpp.i
.PHONY : runtime/ffi.cpp.i

runtime/ffi.s: runtime/ffi.cpp.s
.PHONY : runtime/ffi.s

# target to generate assembly for a file
runtime/ffi.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/runtime/ffi.cpp.s
.PHONY : runtime/ffi.cpp.s

runtime/vm.o: runtime/vm.cpp.o
.PHONY : runtime/vm.o

# target to build an object file
runtime/vm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/runtime/vm.cpp.o
.PHONY : runtime/vm.cpp.o

runtime/vm.i: runtime/vm.cpp.i
.PHONY : runtime/vm.i

# target to preprocess a source file
runtime/vm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/runtime/vm.cpp.i
.PHONY : runtime/vm.cpp.i

runtime/vm.s: runtime/vm.cpp.s
.PHONY : runtime/vm.s

# target to generate assembly for a file
runtime/vm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/runtime/vm.cpp.s
.PHONY : runtime/vm.cpp.s

security/nova_security.o: security/nova_security.cpp.o
.PHONY : security/nova_security.o

# target to build an object file
security/nova_security.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/security/nova_security.cpp.o
.PHONY : security/nova_security.cpp.o

security/nova_security.i: security/nova_security.cpp.i
.PHONY : security/nova_security.i

# target to preprocess a source file
security/nova_security.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/security/nova_security.cpp.i
.PHONY : security/nova_security.cpp.i

security/nova_security.s: security/nova_security.cpp.s
.PHONY : security/nova_security.s

# target to generate assembly for a file
security/nova_security.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/security/nova_security.cpp.s
.PHONY : security/nova_security.cpp.s

standard_library/database/nova_db.o: standard_library/database/nova_db.cpp.o
.PHONY : standard_library/database/nova_db.o

# target to build an object file
standard_library/database/nova_db.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/standard_library/database/nova_db.cpp.o
.PHONY : standard_library/database/nova_db.cpp.o

standard_library/database/nova_db.i: standard_library/database/nova_db.cpp.i
.PHONY : standard_library/database/nova_db.i

# target to preprocess a source file
standard_library/database/nova_db.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/standard_library/database/nova_db.cpp.i
.PHONY : standard_library/database/nova_db.cpp.i

standard_library/database/nova_db.s: standard_library/database/nova_db.cpp.s
.PHONY : standard_library/database/nova_db.s

# target to generate assembly for a file
standard_library/database/nova_db.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/standard_library/database/nova_db.cpp.s
.PHONY : standard_library/database/nova_db.cpp.s

standard_library/finance/nova_finance.o: standard_library/finance/nova_finance.cpp.o
.PHONY : standard_library/finance/nova_finance.o

# target to build an object file
standard_library/finance/nova_finance.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/standard_library/finance/nova_finance.cpp.o
.PHONY : standard_library/finance/nova_finance.cpp.o

standard_library/finance/nova_finance.i: standard_library/finance/nova_finance.cpp.i
.PHONY : standard_library/finance/nova_finance.i

# target to preprocess a source file
standard_library/finance/nova_finance.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/standard_library/finance/nova_finance.cpp.i
.PHONY : standard_library/finance/nova_finance.cpp.i

standard_library/finance/nova_finance.s: standard_library/finance/nova_finance.cpp.s
.PHONY : standard_library/finance/nova_finance.s

# target to generate assembly for a file
standard_library/finance/nova_finance.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/standard_library/finance/nova_finance.cpp.s
.PHONY : standard_library/finance/nova_finance.cpp.s

standard_library/health/nova_health.o: standard_library/health/nova_health.cpp.o
.PHONY : standard_library/health/nova_health.o

# target to build an object file
standard_library/health/nova_health.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/standard_library/health/nova_health.cpp.o
.PHONY : standard_library/health/nova_health.cpp.o

standard_library/health/nova_health.i: standard_library/health/nova_health.cpp.i
.PHONY : standard_library/health/nova_health.i

# target to preprocess a source file
standard_library/health/nova_health.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/standard_library/health/nova_health.cpp.i
.PHONY : standard_library/health/nova_health.cpp.i

standard_library/health/nova_health.s: standard_library/health/nova_health.cpp.s
.PHONY : standard_library/health/nova_health.s

# target to generate assembly for a file
standard_library/health/nova_health.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/standard_library/health/nova_health.cpp.s
.PHONY : standard_library/health/nova_health.cpp.s

system_logs/nova_logger.o: system_logs/nova_logger.cpp.o
.PHONY : system_logs/nova_logger.o

# target to build an object file
system_logs/nova_logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/system_logs/nova_logger.cpp.o
.PHONY : system_logs/nova_logger.cpp.o

system_logs/nova_logger.i: system_logs/nova_logger.cpp.i
.PHONY : system_logs/nova_logger.i

# target to preprocess a source file
system_logs/nova_logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/system_logs/nova_logger.cpp.i
.PHONY : system_logs/nova_logger.cpp.i

system_logs/nova_logger.s: system_logs/nova_logger.cpp.s
.PHONY : system_logs/nova_logger.s

# target to generate assembly for a file
system_logs/nova_logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/system_logs/nova_logger.cpp.s
.PHONY : system_logs/nova_logger.cpp.s

testing/nova_test.o: testing/nova_test.cpp.o
.PHONY : testing/nova_test.o

# target to build an object file
testing/nova_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/testing/nova_test.cpp.o
.PHONY : testing/nova_test.cpp.o

testing/nova_test.i: testing/nova_test.cpp.i
.PHONY : testing/nova_test.i

# target to preprocess a source file
testing/nova_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/testing/nova_test.cpp.i
.PHONY : testing/nova_test.cpp.i

testing/nova_test.s: testing/nova_test.cpp.s
.PHONY : testing/nova_test.s

# target to generate assembly for a file
testing/nova_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/testing/nova_test.cpp.s
.PHONY : testing/nova_test.cpp.s

tooling/nova_tools.o: tooling/nova_tools.cpp.o
.PHONY : tooling/nova_tools.o

# target to build an object file
tooling/nova_tools.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/tooling/nova_tools.cpp.o
.PHONY : tooling/nova_tools.cpp.o

tooling/nova_tools.i: tooling/nova_tools.cpp.i
.PHONY : tooling/nova_tools.i

# target to preprocess a source file
tooling/nova_tools.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/tooling/nova_tools.cpp.i
.PHONY : tooling/nova_tools.cpp.i

tooling/nova_tools.s: tooling/nova_tools.cpp.s
.PHONY : tooling/nova_tools.s

# target to generate assembly for a file
tooling/nova_tools.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/tooling/nova_tools.cpp.s
.PHONY : tooling/nova_tools.cpp.s

ui/nova_ui.o: ui/nova_ui.cpp.o
.PHONY : ui/nova_ui.o

# target to build an object file
ui/nova_ui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/ui/nova_ui.cpp.o
.PHONY : ui/nova_ui.cpp.o

ui/nova_ui.i: ui/nova_ui.cpp.i
.PHONY : ui/nova_ui.i

# target to preprocess a source file
ui/nova_ui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/ui/nova_ui.cpp.i
.PHONY : ui/nova_ui.cpp.i

ui/nova_ui.s: ui/nova_ui.cpp.s
.PHONY : ui/nova_ui.s

# target to generate assembly for a file
ui/nova_ui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/ui/nova_ui.cpp.s
.PHONY : ui/nova_ui.cpp.s

universal_packages/python_bridge/py_interop.o: universal_packages/python_bridge/py_interop.cpp.o
.PHONY : universal_packages/python_bridge/py_interop.o

# target to build an object file
universal_packages/python_bridge/py_interop.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/universal_packages/python_bridge/py_interop.cpp.o
.PHONY : universal_packages/python_bridge/py_interop.cpp.o

universal_packages/python_bridge/py_interop.i: universal_packages/python_bridge/py_interop.cpp.i
.PHONY : universal_packages/python_bridge/py_interop.i

# target to preprocess a source file
universal_packages/python_bridge/py_interop.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/universal_packages/python_bridge/py_interop.cpp.i
.PHONY : universal_packages/python_bridge/py_interop.cpp.i

universal_packages/python_bridge/py_interop.s: universal_packages/python_bridge/py_interop.cpp.s
.PHONY : universal_packages/python_bridge/py_interop.s

# target to generate assembly for a file
universal_packages/python_bridge/py_interop.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nova.dir/build.make CMakeFiles/nova.dir/universal_packages/python_bridge/py_interop.cpp.s
.PHONY : universal_packages/python_bridge/py_interop.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... nova"
	@echo "... advanced_ai_core/ai_core.o"
	@echo "... advanced_ai_core/ai_core.i"
	@echo "... advanced_ai_core/ai_core.s"
	@echo "... analytics/nova_telemetry.o"
	@echo "... analytics/nova_telemetry.i"
	@echo "... analytics/nova_telemetry.s"
	@echo "... blockchain_web3/nova_web3.o"
	@echo "... blockchain_web3/nova_web3.i"
	@echo "... blockchain_web3/nova_web3.s"
	@echo "... compiler/bytecode.o"
	@echo "... compiler/bytecode.i"
	@echo "... compiler/bytecode.s"
	@echo "... compiler/lexer.o"
	@echo "... compiler/lexer.i"
	@echo "... compiler/lexer.s"
	@echo "... compiler/main.o"
	@echo "... compiler/main.i"
	@echo "... compiler/main.s"
	@echo "... compiler/parser.o"
	@echo "... compiler/parser.i"
	@echo "... compiler/parser.s"
	@echo "... deployment/nova_deploy.o"
	@echo "... deployment/nova_deploy.i"
	@echo "... deployment/nova_deploy.s"
	@echo "... docs/nova_docgen.o"
	@echo "... docs/nova_docgen.i"
	@echo "... docs/nova_docgen.s"
	@echo "... experiments/quantum/nova_quantum.o"
	@echo "... experiments/quantum/nova_quantum.i"
	@echo "... experiments/quantum/nova_quantum.s"
	@echo "... full_stack_dev/hyperweb.o"
	@echo "... full_stack_dev/hyperweb.i"
	@echo "... full_stack_dev/hyperweb.s"
	@echo "... game_engine/nova_game.o"
	@echo "... game_engine/nova_game.i"
	@echo "... game_engine/nova_game.s"
	@echo "... graphics/nova_graphics.o"
	@echo "... graphics/nova_graphics.i"
	@echo "... graphics/nova_graphics.s"
	@echo "... hardware_control/embedded_targets/nova_iot.o"
	@echo "... hardware_control/embedded_targets/nova_iot.i"
	@echo "... hardware_control/embedded_targets/nova_iot.s"
	@echo "... ide/vscode_extension/nova_lsp.o"
	@echo "... ide/vscode_extension/nova_lsp.i"
	@echo "... ide/vscode_extension/nova_lsp.s"
	@echo "... networking/nova_network.o"
	@echo "... networking/nova_network.i"
	@echo "... networking/nova_network.s"
	@echo "... operating_system_layer/j_kernel.o"
	@echo "... operating_system_layer/j_kernel.i"
	@echo "... operating_system_layer/j_kernel.s"
	@echo "... package_ecosystem/nova_pm.o"
	@echo "... package_ecosystem/nova_pm.i"
	@echo "... package_ecosystem/nova_pm.s"
	@echo "... physics_engine/nova_physics.o"
	@echo "... physics_engine/nova_physics.i"
	@echo "... physics_engine/nova_physics.s"
	@echo "... robotics_control/robot_core.o"
	@echo "... robotics_control/robot_core.i"
	@echo "... robotics_control/robot_core.s"
	@echo "... runtime/ffi.o"
	@echo "... runtime/ffi.i"
	@echo "... runtime/ffi.s"
	@echo "... runtime/vm.o"
	@echo "... runtime/vm.i"
	@echo "... runtime/vm.s"
	@echo "... security/nova_security.o"
	@echo "... security/nova_security.i"
	@echo "... security/nova_security.s"
	@echo "... standard_library/database/nova_db.o"
	@echo "... standard_library/database/nova_db.i"
	@echo "... standard_library/database/nova_db.s"
	@echo "... standard_library/finance/nova_finance.o"
	@echo "... standard_library/finance/nova_finance.i"
	@echo "... standard_library/finance/nova_finance.s"
	@echo "... standard_library/health/nova_health.o"
	@echo "... standard_library/health/nova_health.i"
	@echo "... standard_library/health/nova_health.s"
	@echo "... system_logs/nova_logger.o"
	@echo "... system_logs/nova_logger.i"
	@echo "... system_logs/nova_logger.s"
	@echo "... testing/nova_test.o"
	@echo "... testing/nova_test.i"
	@echo "... testing/nova_test.s"
	@echo "... tooling/nova_tools.o"
	@echo "... tooling/nova_tools.i"
	@echo "... tooling/nova_tools.s"
	@echo "... ui/nova_ui.o"
	@echo "... ui/nova_ui.i"
	@echo "... ui/nova_ui.s"
	@echo "... universal_packages/python_bridge/py_interop.o"
	@echo "... universal_packages/python_bridge/py_interop.i"
	@echo "... universal_packages/python_bridge/py_interop.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

